name: Docker Image CI - svg-gen

on:
  push:
    paths:
      - "svg-gen/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and Push svg-gen Image
        run: |
          docker build ./svg-gen --file svg-gen/Dockerfile --tag ghcr.io/hannahellis4242/owt/svggen:latest
          docker push ghcr.io/hannahellis4242/owt/svggen:latest
